### ISSUE TITLE
make template project

### ISSUE THREAD

**Issue by koudyk** [neurodatascience/labelbuddy-annotations#26]
Comments from Jérôme:
- if you add documents, don't add full articles but just a couple placeholder very short documents. 
  - remind that those are not generated manually but by pubget. 
- if you add labels, point out that they can be generated in labelbuddy rather than editing the file directly. 
- if you just want to add the directories without example files, you can put a short readme in each directory (if the directory is completely empty git will not do anything with it, as it tracks regular files and symbolic links but not directories)
- as you add the template readme you can also check and edit the "contributing to this repository" docs: https://neurodatascience.github.io/labelbuddy-annotations/contributing_to_this_repository.html#adding-a-new-project

**Comment by koudyk** [comment]
@jeromedockes ,
I added the template project README and skeleton structure. If you think it's okay, then I'll go ahead and update the README's for each project. see this [commit](https://github.com/neurodatascience/labelbuddy-annotations/commit/6b31f3ff8489c6fcdc2d047bb6dc55c5a9a616a8)

I also changed to code to make the database so that it would ignore the template project. I'm not sure if I did this in the best way - could you check? see this [commit](https://github.com/neurodatascience/labelbuddy-annotations/commit/74794a858e52123b1b09c076d27311d053832cf7)

**Comment by jeromedockes** [comment]
thanks! yes the README looks good, I just made a couple of small changes and added a mention of the `datasets.json` file. I also updated the `database` module
