### ISSUE TITLE
error when opening interactive plot from Binder instance of run_display_csv.ipynb

### ISSUE THREAD

**Issue by koudyk** [neurodatascience/labelbuddy-annotations#3]
I created a Binder instance of a jupyter notebook that runs a python file that creates an interactive plot (complicated, I know, but I couldn't think of how else to let people easily open the interactive plot).

I got the Binder notebook working, but the interactive app won't open

This is the error that I get in my Firefox browser:
```
Unable to connect

Firefox can’t establish a connection to the server at 127.0.0.1:8050.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
```

**Comment by jeromedockes** [comment]
Hi Kendra, I could display your figure locally it's very cool! I think having a
small gallery of notebooks that can be run either locally or on binder is a
great idea. And we can also render them eg with sphinx gallery to display them
in a github pages website.

Re. this error message, 127.0.0.1 is the address for loopback traffic (it is
often given the name localhost), ie packets sent to this address never make it
to the network interface but are sent back to your own machine. It is used to
access services running on your own machine.

When you run the Dash app on your computer, it starts a server application that
listens on the loopback address, so you can open the figure by pointing firefox
to localhost:8050. If you started the Dash app on another machine (ie one of
mybinder's servers), nothing is listening on localhost:8050 on your machine, so
if you point firefox to this address it tells you it cannot establish a
connection.

The easiest way as we don't want to host a web service would be to use dash or
plain plotly without running a flask app, ie relying on client-side callbacks
for interactivity.

jupyter widgets and possibly voilà are also a convenient way of building
interactive components in a notebook; for example you can have a look at
https://github.com/neuroquery/neuroquery_apps

I'm away this weekend but we can talk more about this at the beginning of next
week!

**Comment by jeromedockes** [comment]
or you can use https://github.com/plotly/jupyter-dash to embed the Dash app directly in the notebook, then it would work on binder

**Comment by jeromedockes** [comment]
to simplify we decided we put only static content online now, the app is still available in the repository for anyone wanting to run it locally
