### ISSUE TITLE
connect database to paper metadata (e.g., publication year)?

### ISSUE THREAD

**Issue by koudyk** [neurodatascience/labelbuddy-annotations#7]
Should we connect the annotation database to one with other paper metadata? Such as the publication year and journal?

**Comment by jeromedockes** [comment]
> Should we connect the annotation database to one with other paper metadata? Such as the publication year and journal?

we may need to eventually, but if it is just the publication year and
journal we can easily read those from the jsonl files themselves.

they can be found in the doc["text"] at the locations indicated in the
corresponding field in doc["metadata"]["field_positions"].
I'll add that to the script that creates the database.

**Comment by jeromedockes** [comment]
I added the year, journal and title

**Comment by koudyk** [comment]
Thanks! and sorry I didn't realize it was already there
