### ISSUE TITLE
installing annotutils in -e mode requires setup.py file

### ISSUE THREAD

**Issue by koudyk** [neurodatascience/labelbuddy-annotations#8]
```bash
(venv) ~/projects/labelbuddy-annotations (main)$ pip install -e analysis/annotutils/
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/kendra/projects/labelbuddy-annotations/analysis/annotutils
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

Also, the instructions have a typo in the folder name. 
It says "Install it with pip install -e analysis/**annotatutils**"
But it should be "Install it with pip install -e analysis/**annotutils**
I assume you just changed your mind about the name at some point.

**Comment by koudyk** [comment]
I created a setup.py file, and now I can install it in -e mode, and I can run the annotations_summary.py file (the overview on the website)

**Comment by jeromedockes** [comment]
> ```bash
> (venv) ~/projects/labelbuddy-annotations (main)$ pip install -e analysis/annotutils/
> ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/kendra/projects/labelbuddy-annotations/analysis/annotutils
> (A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
> ```
>

I think you just need to upgrade pip and setuptools

> Also, the instructions have a typo in the folder name. 
> It says "Install it with pip install -e analysis/**annotatutils**"
> But it should be "Install it with pip install -e analysis/**annotutils**

yes it's a typo!

**Comment by jeromedockes** [comment]
> I created a setup.py file, and now I can install it in -e mode, and I can run the annotations_summary.py file (the overview on the website) 

when it's not necessary required new python packages avoid having a
setup.py and rely on setup.cfg and pyproject.toml instead
